export {default as News} from "./News"
export {default as Calender} from "./Calender"
export {default as Weather} from "./Weather"
export {default as Modal} from "./NewsModal"
export {default as BookMark} from "./Bookmarks"
export {default as Blogs} from "./Blogs"